[tool.flet]

[tool.flet.app]
# Cấu hình cơ bản
name = "QuanLyDoanHoi"
description = "Ứng dụng quản lý đoàn viên"
module = "main"

# ICON - quan trọng nhất
icon = "assets/icon.png"

# Metadata bổ sung
[tool.flet.app.windows]
product = "Quản lý Đoàn - Hội"
company = "Le Quang Anh"
copyright = "Copyright © 2026 Le Quang Anh. All rights reserved."
file_version = "1.6.0.0"